[package]
name = "abstract-ws"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
url = "2.1.1"
futures = { version = "0.3.5", default-features = false }
